# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a9aa1314926561e4eaaac178f8778044fb3803da78b7e3fd890abd5c35ae735cf10c6549ed76bd045579b1edde93dc1cd84b1bf72e26473909665b341657183

test:
  secret_key_base: 0c9977fd198b3208a3739e6244f71c206445f619764babfed388799e9290f61fc444ed13c155e7fac659c0b2798d0e3833265ef3883da8feac6bdc0f72ea0da6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
